all: 

clean:
	
install_dependencies:
	sudo apt install python3-opencv
	sudo add-apt-repository ppa:ubuntuhandbook1/ppa
	sudo add-apt-repository ppa:rock-core/qt4
	sudo apt-get update
	sudo apt-get install libqtcore4
	sudo apt-get install libqt4-network --fix-missing
	sudo apt-get install libqt4-qt3support
	sudo apt remove gstreamer1.0-vaapi

